_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

# CaptainCourierCaptainBundle:
#     resource: "@CaptainCourierCaptainBundle/Controller"
#     type: annotation

logout:
    path:   /addresses/logout

captainCourierCaptain:
    prefix: /
    resource: "@CaptainCourierCaptainBundle/Resources/config/routing.yml"


# address:
#     type: rest
#     resource: "CaptainCourier\\CaptainBundle\\Controller\\AddressController"

# parcel:
#     type: rest
#     resource: "CaptainCourier\\CaptainBundle\\Controller\\ParcelController"

item:
    type: rest
    resource: "CaptainCourier\\CaptainBundle\\Controller\\ItemController"

customsInfo:
    type: rest
    resource: "CaptainCourier\\CaptainBundle\\Controller\\CustomsInfoController"


shipment:
    type: rest
    resource: "CaptainCourier\\CaptainBundle\\Controller\\ShipmentController"